export function Privacy() {
  return (
    <main className="bg-white min-h-screen text-slate-900 font-inter selection:bg-blue-50">
      <div className="max-w-4xl mx-auto px-6 py-24">
        <h1 className="text-4xl font-bold text-slate-900 mb-4 tracking-tight">
          Privacy Policy
        </h1>
        <p className="text-slate-500 mb-16 font-medium">
          Last updated: January 2025
        </p>

        <div className="space-y-12 text-slate-600 leading-relaxed">
          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-slate-900">
              1. Information We Collect
            </h2>
            <p>
              We collect information to provide and improve our services. This includes:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Account Information:</strong> Name, email address, and contact details.</li>
              <li><strong>Meeting Data:</strong> Audio recordings, transcripts, and summaries generated by our AI.</li>
              <li><strong>Usage Data:</strong> Information about how you interact with our platform.</li>
            </ul>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-slate-900">
              2. How We Use Your Information
            </h2>
            <p>
              We use the collected data for the following purposes:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>To provide, maintain, and improve our services.</li>
              <li>To generate meeting summaries and extract action items.</li>
              <li>To communicate with you about updates and support.</li>
              <li>To ensure the security and integrity of our platform.</li>
            </ul>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-slate-900">
              3. Data Security
            </h2>
            <p>
              We implement industry-standard security measures to protect your data. All transmissions
              are encrypted using TLS, and stored data is protected with AES-256 encryption. We utilize
              multi-layered safeguards to prevent unauthorized access.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-slate-900">
              4. Data Sharing
            </h2>
            <p>
              We do not sell your personal data. We may share information only in the following circumstances:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>With your explicit consent.</li>
              <li>To comply with legal obligations.</li>
              <li>With trusted service providers who assist in operating our platform (under strict confidentiality agreements).</li>
            </ul>
          </section>

          <div className="pt-12 border-t border-slate-200">
            <p className="text-sm text-slate-400">
              If you have concerns about your data, please contact our Data Protection Officer.
            </p>
          </div>
        </div>
      </div>
    </main>
  )
}
